/**
 * Tag all visible artworks with hybrid vision + text analysis.
 * Fetches images, analyzes with Claude vision, extracts themes from artist statements.
 * Writes tags to autoGeneratedTags field in DB. Only processes assets that
 * don't have tags yet (see the `autoGeneratedTags: null` filter below), so
 * this is safe to re-run — it never re-tags (or re-bills for) existing work.
 *
 * Run: npx tsx scripts/tag-all-artwork.ts
 * Also runs automatically every 3 months via .github/workflows/tag-artwork.yml
 *
 * Split into two API calls per artwork (vision-only, then text-only) rather
 * than one combined call — this is what got tagging from ~91% to 100%
 * success across the full library; a single combined call was prone to
 * response truncation and JSON parse failures on longer artist statements.
 *
 * Cost: ~$0.02-0.04/artwork (claude-sonnet-4-6). ~$4 to tag the initial
 * 207-artwork library; budget ~$6/year at 100-200 new artworks/year.
 */
import { config } from "dotenv";
import { resolve } from "node:path";
import { prisma } from "@/lib/db";
import { getSignedR2Url } from "@/lib/storage/r2";
import Anthropic from "@anthropic-ai/sdk";
import https from "node:https";

config({ path: resolve(process.cwd(), ".env.local") });

const client = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

interface TagResult {
  visionConcrete: string[];
  visionInterpretive: string[];
  dominantColors: string[];
  subjects: string[];
  textThemes: string[];
  combined: string[];
}

async function fetchImageAsBase64(url: string, retries: number = 3): Promise<string> {
  return new Promise((resolve, reject) => {
    const attempt = () => {
      https
        .get(url, { timeout: 10000 }, (res) => {
          if (res.statusCode === 404) {
            reject(new Error("404: Image not found in R2"));
            return;
          }
          if (res.statusCode && res.statusCode >= 400) {
            reject(new Error(`HTTP ${res.statusCode}`));
            return;
          }

          const chunks: Buffer[] = [];
          res.on("data", (chunk: Buffer) => chunks.push(chunk));
          res.on("end", () => {
            const buffer = Buffer.concat(chunks);
            resolve(buffer.toString("base64"));
          });
        })
        .on("error", (err) => {
          if (retries > 0) {
            setTimeout(attempt, 1000);
          } else {
            reject(err);
          }
        });
    };
    attempt();
  });
}

// Sanitize title/artist to avoid JSON parsing issues with special chars
function sanitizeForPrompt(text: string): string {
  return text
    .replace(/\\/g, "\\\\") // Escape backslashes first
    .replace(/"/g, '\\"') // Escape quotes
    .replace(/\n/g, " "); // Remove newlines
}

async function tagArtwork(
  assetId: string,
  imageBase64: string,
  artistName: string,
  title: string,
  coverLetter: string,
): Promise<{ tags: TagResult; tokens: { input: number; output: number } }> {
  const textContext = coverLetter.slice(0, 1500) || "(no artist statement)";
  const safeArtist = sanitizeForPrompt(artistName);
  const safeTitle = sanitizeForPrompt(title);
  const totalTokens = { input: 0, output: 0 };

  // Step 1: Vision analysis only (higher max_tokens for vision)
  const visionResponse = await client.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 1500,
    messages: [
      {
        role: "user",
        content: [
          {
            type: "image",
            source: {
              type: "base64",
              media_type: "image/webp",
              data: imageBase64,
            },
          },
          {
            type: "text",
            text: `Analyze the visual elements of this artwork: "${safeTitle}"

Return ONLY valid JSON with these exact fields (vision analysis only):
{
  "visionConcrete": ["medium/technique", "subject matter", "composition", "style", "color palette"],
  "visionInterpretive": ["mood", "aesthetic", "what the image evokes", "visual themes", "feeling"],
  "dominantColors": ["actual color names visible", "e.g. cadmium red, ultramarine"]
}

Be specific. Only analyze what you see visually.`,
          },
        ],
      },
    ],
  });

  totalTokens.input += visionResponse.usage.input_tokens;
  totalTokens.output += visionResponse.usage.output_tokens;

  // Step 2: Text analysis only (artist statement themes)
  const textResponse = await client.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 800,
    messages: [
      {
        role: "user",
        content: [
          {
            type: "text",
            text: `Artwork: "${safeTitle}" by ${safeArtist}

Artist's statement:
${sanitizeForPrompt(textContext)}

Extract conceptual themes and artist's intent. Return ONLY valid JSON:
{
  "subjects": ["what's depicted based on context", "e.g. sleeping figures, power lines, collage fragments"],
  "textThemes": ["conceptual ideas from statement", "recurring themes", "artist's intent", "movement/tradition"]
}`,
          },
        ],
      },
    ],
  });

  totalTokens.input += textResponse.usage.input_tokens;
  totalTokens.output += textResponse.usage.output_tokens;

  // Parse both responses
  const parseJSON = (text: string) => {
    let jsonText = text.trim();
    const jsonMatch = jsonText.match(/```(?:json)?\s*([\s\S]*?)```/);
    if (jsonMatch) {
      jsonText = jsonMatch[1].trim();
    } else if (jsonText.startsWith("```")) {
      jsonText = jsonText.slice(3).replace(/```$/, "");
    }
    jsonText = jsonText.trim();

    try {
      return JSON.parse(jsonText);
    } catch (e) {
      const lastBrace = jsonText.lastIndexOf("}");
      if (lastBrace > 0) {
        return JSON.parse(jsonText.slice(0, lastBrace + 1));
      }
      throw e;
    }
  };

  const visionContent = visionResponse.content[0];
  if (visionContent.type !== "text") {
    throw new Error("Unexpected vision response type");
  }

  const textContent = textResponse.content[0];
  if (textContent.type !== "text") {
    throw new Error("Unexpected text response type");
  }

  const visionTags = parseJSON(visionContent.text);
  const textTags = parseJSON(textContent.text);

  // Merge vision and text analysis results
  const tags: TagResult = {
    visionConcrete: visionTags.visionConcrete || [],
    visionInterpretive: visionTags.visionInterpretive || [],
    dominantColors: visionTags.dominantColors || [],
    subjects: textTags.subjects || [],
    textThemes: textTags.textThemes || [],
    combined: [], // Will be populated below
  };

  // Ensure combined is a flattened, deduplicated, sorted list
  const allTags = [
    ...tags.visionConcrete,
    ...tags.visionInterpretive,
    ...tags.dominantColors,
    ...tags.subjects,
    ...tags.textThemes,
  ];
  tags.combined = Array.from(new Set(allTags)).sort();

  return {
    tags,
    tokens: totalTokens,
  };
}

async function main() {
  console.log("🎨 Tagging all visible artworks with hybrid vision + text analysis\n");

  // Load all visible artAssets with cover letters - only those without tags (retry failed ones)
  console.log("[1] Loading visible artAssets without tags from database…");
  const assets = await prisma.artAsset.findMany({
    where: {
      visibleInArtLibrary: true,
      autoGeneratedTags: null, // Only retry artworks that failed
    },
    include: {
      submission: {
        select: {
          artistName: true,
          submissionTitle: true,
          coverLetter: true,
        },
      },
    },
    orderBy: [{ submissionId: "asc" }, { fileIndex: "asc" }],
  });

  console.log(`✓ Loaded ${assets.length} artAssets\n`);

  // DEBUG: Test mode - only process first 3 assets to diagnose issues
  const testMode = process.argv.includes("--test");
  if (testMode) {
    console.log("🧪 TEST MODE: Processing first 3 assets only\n");
    assets.length = 3;
  }

  let totalInputTokens = 0;
  let totalOutputTokens = 0;
  let successCount = 0;
  let failureCount = 0;

  // Process each asset sequentially
  for (let i = 0; i < assets.length; i++) {
    const asset = assets[i];
    const progress = `${i + 1}/${assets.length}`;

    process.stdout.write(
      `[${progress}] ${(asset.submission.submissionTitle ?? "Untitled").slice(0, 40).padEnd(40)} … `,
    );

    try {
      // Get signed URL for the large image
      const imageUrl = await getSignedR2Url(asset.storagePathLarge);

      if (testMode && i < 1) {
        console.log(`  DEBUG: Fetching URL: ${imageUrl.slice(0, 80)}...`);
      }

      // Fetch image as base64
      const imageBase64 = await fetchImageAsBase64(imageUrl);

      if (testMode && i < 1) {
        console.log(`  DEBUG: Base64 length: ${imageBase64.length} bytes`);
      }

      // Generate tags
      const { tags, tokens } = await tagArtwork(
        asset.id,
        imageBase64,
        asset.submission.artistName || "Unknown",
        asset.submission.submissionTitle || "Untitled",
        asset.submission.coverLetter || "",
      );

      totalInputTokens += tokens.input;
      totalOutputTokens += tokens.output;

      // Write to database immediately
      await prisma.artAsset.update({
        where: { id: asset.id },
        data: {
          autoGeneratedTags: JSON.stringify(tags),
        },
      });

      console.log("✓");
      successCount++;
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : String(err);
      if (testMode) {
        console.log(`\n  FULL ERROR: ${errMsg.slice(0, 500)}`);
      }
      console.log(`✗ ${errMsg.slice(0, 40)}`);
      failureCount++;
    }
  }

  // Final report
  console.log("\n" + "━".repeat(70));
  console.log("📊 Tagging complete:");
  console.log(`   ✓ Successful: ${successCount}/${assets.length}`);
  if (failureCount > 0) {
    console.log(`   ✗ Failed: ${failureCount}`);
  }

  console.log("\n💰 Token usage:");
  console.log(`   Input tokens: ${totalInputTokens.toLocaleString()}`);
  console.log(`   Output tokens: ${totalOutputTokens.toLocaleString()}`);
  console.log(`   Total: ${(totalInputTokens + totalOutputTokens).toLocaleString()} tokens`);

  const totalCost = (totalInputTokens * 3) / 1_000_000 + (totalOutputTokens * 15) / 1_000_000;
  console.log(`   Estimated cost: $${totalCost.toFixed(2)}`);

  const avgPerImage = (totalInputTokens + totalOutputTokens) / successCount;
  console.log(`   Avg per image: ${Math.round(avgPerImage).toLocaleString()} tokens`);

  console.log("\n✓✓✓ All visible artworks tagged and stored in database.");
}

main()
  .catch((err) => {
    console.error("\n✗ TAGGING FAILED:\n", err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
