/**
 * Write approved tags from tag-results.json to the database.
 *
 * Run: npx tsx scripts/write-tags.ts [path-to-results.json]
 *
 * Defaults to ./tag-results.json if no path provided.
 * Only writes the exact asset IDs + tags from the results file.
 */
import { resolve } from "node:path";
import { readFileSync } from "node:fs";
import { prisma } from "@/lib/db";

interface Result {
  id: string;
  tags: {
    concreteTags: string[];
    interpretiveTags: string[];
  };
}

interface ResultsFile {
  results: Result[];
}

async function main() {
  const resultsPath =
    process.argv[2] || resolve(process.cwd(), "tag-results.json");

  console.log(`📂 Reading results from: ${resultsPath}\n`);

  let data: ResultsFile;
  try {
    data = JSON.parse(readFileSync(resultsPath, "utf-8"));
  } catch (err) {
    console.error(
      `✗ Failed to read or parse file: ${err instanceof Error ? err.message : String(err)}`,
    );
    process.exit(1);
  }

  if (!data.results || !Array.isArray(data.results)) {
    console.error("✗ Invalid results file format (missing results array)");
    process.exit(1);
  }

  console.log(`🏷️  Writing ${data.results.length} tagged assets to database...\n`);

  let written = 0;
  for (const result of data.results) {
    try {
      const tagsJson = JSON.stringify(result.tags);
      await prisma.artAsset.update({
        where: { id: result.id },
        data: { autoGeneratedTags: tagsJson },
      });
      console.log(
        `✓ Updated asset ${result.id}: ${result.tags.concreteTags.length} concrete + ${result.tags.interpretiveTags.length} interpretive tags`,
      );
      written++;
    } catch (err) {
      console.error(
        `✗ Failed to write asset ${result.id}: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  }

  console.log(`\n✓✓✓ Wrote ${written}/${data.results.length} assets to database.`);
}

main()
  .catch((err) => {
    console.error("\n✗ WRITE FAILED:\n", err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
